### ISSUE TITLE
Does not resize after clearing the contents of text area

### ISSUE THREAD

**Issue by asacarter** [jackmoore/autosize#165]
If the contents of a textarea are emptied, it does not automatically shrink to it's minimum size, even after initializing the plugin on the element again.

`$('#message').val('');`
and
`$('#message').val('').autosize();`

**Comment by sn3p** [comment]
Same problem here, too bad autosize doesn't take care of this.
But `autosize.update(textarea);` saved the day.

**Comment by jackmoore** [comment]
@asacarter I'll have to look into having it correctly size if you re-initialize the plugin because that's an oversight.  But, as for making it resize automatically there is probably no practical way to do that.  The script would have to resort to something like polling, because there is no event that is triggered when directly setting the value of the value property.
