### ISSUE TITLE
Using data-autosize on input disables functionality

### ISSUE THREAD

**Issue by marckohlbrugge** [jackmoore/autosize#200]
I tried using `$('textarea[data-autosize]').autosize()` so I could enable autosizing on any `textarea` by simply adding the right data attribute. This didn't work for some reason.

After some trial and error I figured out that autosize already uses that attribute internally to keep track of stuff.

I recommend clarifying in this README or by using another name that's less likely to be used. I'd be happy to send a pull request for the README if you think it's a good addition.

**Comment by kirkbushell** [comment]
@marckohlbrugge in addition, data really should be used for data attributes. I'd use a class or identifier rather than a data attribute.

**Comment by joaocunha** [comment]
:+1:.

A stateful name would make more sense, like `[data-is-autosize]` or `[data-autosize-enabled]`.

**Comment by jackmoore** [comment]
Yeah, sorry about the lack of documentation on this.  I hate to clutter the docs with such minutia, so I tried to make it more specific using `data-autosize-on` to avoid collisions.  I would like to be able to use something like [the Set object](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set) to keep track of elements, instead of flagging it with a property, but browser support isn't quite there yet.
