### ISSUE TITLE
Textarea set to 0px height sometimes

### ISSUE THREAD

**Issue by ChristianPeters** [jackmoore/autosize#203]
Hi,

I want to use autosize 2 for in-place editing. So there is a div (`.editable-content-display`) with text and on click it gets exchanged with a textarea (`.editable-content-field`), which gets focused:

``` coffeescript
   $('.editable-content-display')
      .on 'click', (e) ->
          $(@)
            .hide()
            .nextAll('.editable-content-form').first()
              .show()
              .find('.editable-content-field').focus()
        e.stopPropagation()

    $('.editable-content-field')
      .on 'focus', ->
        autosize $(@)
      .on 'blur', ->
        $(@).closest('.editable-content-form')
          .submit()
          .hide()
          .prevAll('.editable-content-display').first().show()
```

Works like a charm. Most of the time.
Sometimes, the textarea is set to a height of 0px by autosize. If this phenomenon occurs, I can reproduce it as often as I want by toggling the textarea display – until I reload the page. I have plenty of those in-place editable fields on my page but only one or two of them show this phenomenon at the same time. I observed it in both Chrome and Firefox.

Sadly, I cannot reproduce it if I want to. I suspect some kind of raise condition but I got no clue...

![autosize_2px_height](https://cloud.githubusercontent.com/assets/56810/6451031/1da8620e-c12c-11e4-849e-ed4634840bab.jpg)
When I made this screenshot (the textarea is marked; the rest is distorted; it's blue because I accidentally marked the whole page), the textarea got a height of 2px. After adding some styles, it has been 0px for the last 3 times.

Do you have any hint in which direction I may look for the bug? Is there a situation where the height gets set to (nearly) zero? Does the textarea lose its height when hidden? What would you try to test if this happens again?

Thanks for your time.

**Comment by jackmoore** [comment]
> Sadly, I cannot reproduce it if I want to. I suspect some kind of raise condition but I got no clue

My guess is that this how to do with how the browser is batching operations that trigger a reflow.  At the time the you assign Autosize to the textarea element, it's likely that the document hasn't reflowed yet to reflect the layout changes from calling `.show()`.  Autosize needs the textarea to be non-hidden in order to accurately measure the height and scrollTop, so that reflow needs to happen before it can do it's job.

My suggestion would be to force a reflow after calling `.show()` and see if that resolves the issue. There are various things that can trigger a repaint.  Here is an example using `offsetWidth`:

```
   $('.editable-content-display')
      .on 'click', (e) ->
          $(@)
            .hide()
            .nextAll('.editable-content-form').first()
              .show()
              .find('.editable-content-field').focus()
        e.stopPropagation()

    $('.editable-content-field')
      .on 'focus', ->
        @.offsetWidth;
        autosize $(@)
      .on 'blur', ->
        $(@).closest('.editable-content-form')
          .submit()
          .hide()
          .prevAll('.editable-content-display').first().show()
```

The only thing I changed was to include `@.offsetWidth`.  In order to give an accurate offsetWidth, the browser knows it must go ahead and apply any changes that impact layout.

**Comment by ChristianPeters** [comment]
Okay, seems like a valid guess, thanks.

I cannot confirm that the problem is gone yet. I have been in a state where I could observe the issue, but destroying the autosize and refocusing alone always has been enough to eliminate the issue.

Well, I am optimistic and close the issue. Thanks you very much!
