### ISSUE TITLE
minified warnings

### ISSUE THREAD

**Issue by Daijobou** [jackmoore/autosize#204]
Hello. Thanks for your great work! :)

In http://closure-compiler.appspot.com/home I get 2 warnings for the minified version and one warning for the source version:
~~~~~
JSC_USELESS_CODE: Suspicious code. The result of the 'getprop' operator is not being used. at line 47 character 3
ta.offsetWidth;
~~~~~
Is it possible to clean warnings? :)

**Comment by jackmoore** [comment]
The closure compiler is correct to be suspicious, but the code is intentional.  While I don't have any use for the value returned by `offsetWidth`, the act of getting the value forces the browser to do a reflow, which is necessary to achieve a particular work-around.  It's documented in the unminified source.
