### ISSUE TITLE
Dynamically created textareas does not autosize.

### ISSUE THREAD

**Issue by prem11** [jackmoore/autosize#208]
I created more textareas dyamically using jquerys button onclick function. The textareas are created but they donot autosize. Ca you please help me with this . 

Thank you.

**Comment by jackmoore** [comment]
Autosize only works on the elements that are in the document at the time you assign it, not future elements or elements that are removed from the DOM.  If you create a new textarea you need to either assign Autosize to it after, or setup a system where autosize is automatically assigned based on some event (such as assigning it onFocus).

For example, instead of doing this:
```
$('<textarea/>').appendTo(document.body);
```

You could do something like this:
```
$('<textarea/>')appendTo(document.body).autosize();
```

Or just re-assign to all textarea elements (autosize will automatically skip elements it has already been assigned to).
```
// dynamically insert new HTML
$('textarea').autosize();
```

**Comment by prem11** [comment]
thank you very much...

**Comment by superKalo** [comment]
Hello guys,

One more solution I found, using jQuery:
```html
<textarea data-auto-expand></textarea>
```
```javascript
$(document).on('focus', '[data-auto-expand]', function(){
    autosize($('[data-auto-expand]'));
});
```
So each time the user focuses on a select, all new textarea elements are autosized (as @jackmoore said, autosize will automatically skip elements it has already been assigned to, so we are all good).
