### ISSUE TITLE
Initial height of textarea that has its height set by css selector rule. 

### ISSUE THREAD

**Issue by vogdb** [jackmoore/autosize#217]
Hi! @jackmoore. Thank you for such huge update and improvement. Currently I'm testing the new version 3.0 and have problems with understanding of how the initial height of textarea works. I want my textarea to look like a usual input text at the beginning while it's empty and user haven't typed there yet. For that I put a css rule on the textarea like this
```css
textarea.empty {
  height: 30px
}
```

But unfortunately this rule isn't preserved because autosize plugin sets `height` to `auto` during its `update` function. What should I do in that case?

Here is the full example that you can paste in the `example` dir of the library. In it you can see that the `height: 20px` doesn't work and `height` is set to `48px`.
```html
<!DOCTYPE html>
<html>
	<head>
		<meta charset='utf-8'/>
		<title>Simple Autosize for textareas</title>
		<style>
			textarea {
				padding: 10px;
				vertical-align: top;
				width: 200px;
				height: 20px;
			}
			textarea:focus {
				outline-style: solid;
				outline-width: 2px;
			}
		</style>
	</head>
	<body>
		<h3>max-height 300px</h3>
		<textarea style='max-height: 300px'></textarea>
	</body>
	<script src='../dest/autosize.js'></script>
	<script>
		autosize(document.querySelectorAll('textarea'));
	</script>
</html>
```

I did the first post of this issue accidentally earlier, so you probably will see the strange mess text in your mail. Sorry about that.

**Comment by jackmoore** [comment]
Autosize is going to calculate it's own value for the height, ignoring the height value you set in your CSS.  If you want to set a minimum height, use the CSS min-height or set an appropriate number of rows for the rows attribute on your textarea element.

If you are curious about the numbers, autosize calculated that the height should be 26px.  This is also what the height of the textarea would have been if you hadn't set a height nor used autosize.  That 26px is based on the multiplying the number of rows (2 by default) by the line-height (1.3 by default).  The height isn't actually 48px, because that other 22px is coming from padding and border-width, and the box-sizing model is set to the default content-box.

**Comment by vogdb** [comment]
Thank you for the explanation!

**Comment by rafaelzuckerberg** [comment]
I use this line code in css textarea.materialize-textarea{height: 6rem;}
