### ISSUE TITLE
Height is more always "rows + 1" in version 3

### ISSUE THREAD

**Issue by arteme** [jackmoore/autosize#220]
Hi,

In version 2 of autosize you were able to specify the exact size of textarea in rows via the rows attribute. Example: https://jsfiddle.net/ewjc0gfp/1/

In version 3 of autosize the height of the text area seems to be "the number in rows attribute" + 1. Example: https://jsfiddle.net/gb6z10h2/1/

The documentation at http://www.jacklmoore.com/autosize/ still suggests that rows="1" will produce a textarea with height of one row.

**Comment by cfed** [comment]
@arteme If your issue is specific to firefox if may be due to the extra row issue mentioned here. http://stackoverflow.com/questions/7695945/height-of-textarea-does-not-match-the-rows-in-firefox

The following resolved this issue for me. 
```css
textarea {
height: 30px; // or whatever you want
overflow-x: none;
}
```

**Comment by arteme** [comment]
@cfed The issue is indeed Firefox-specific. Thank you for the link to SO question. The second answer there is especially useful. If we look at the `overflow-x` attribute, then having `overflow-x: hidden` actually does the trick.

And indeed, with autosize version 2, textarea has the followinf CSS:
```css
overflow-x: hidden;
overflow-y: hidden;
resize: horizontal;
word-wrap: break-word;
height: 14px;
```
With autosize version 3, textarea has the following:
```css
resize: horizontal;
height: 30px;
overflow-y: hidden;
```

**Comment by jackmoore** [comment]
@cfed and @arteme, Thanks for the info, that was very helpful. I didn't realize Firefox was doing that.

It looks like Firefox isn't adding any extra row, but reserving space for the scrollbar.  If no text is overflowing the visible area, then it doesn't show the scrollbar but it allocates space for it anyway so that it doesn't have to reflow the text or resize the textarea once the scrollbar does need to be visible.  I think that was probably a good idea on their part.  This is similar to what IE does for the vertical scrollbar, except IE shows the vertical scrollbar as grayed out, instead of having no visibility.  Chrome uses all of the available space and will reflow the text to make room for the scrollbars when they need to be visible, resulting in a lot of jostling around of text when the value switches between having overflow.

I removed the x-overflow (which necessitated setting a word-break), thinking that setting that style was unnecessary now that the script no longer uses a mirror text-area element.  And in a way, that's still true.  The script is calculating and setting the correct height, which means it's working properly within it's scope.  I need to decide if I want to set the x-overflow to hidden in order to normalize Firefox to how Chrome looks, or let that be up to the user to set that in their own CSS.

**Comment by jackmoore** [comment]
Committed and update that makes it optional if the script should set the x and y overflows, but the default behavior should now give you the appearance in Firefox that you are looking for.  Just replace your current script file with the new one.
