### ISSUE TITLE
IE Scrollbars on overflowY = "visible"

### ISSUE THREAD

**Issue by JoeMoon5** [jackmoore/autosize#226]
I'm using the autosize plugin for our company intranet site, and our desktops have IE 10 and Chrome (latest version) installed.

In IE 10, I get visible, disabled scrollbars using the autosize plugin 3.0.2. I was using 1.8 previously and did not experience this issue. My temp work around was to change the following lines of code, located around line 86 in the `update()` function, replacing 'visible' with 'hidden'.

```
if (style.height !== ta.style.height) {
    if (ta.style.overflowY !== 'visible') {
        changeOverflow('visible');
        return;
    }
} 
```

Chrome and Firefox do not have this issue. I'm not able to test on IE 11. My temp fix doesn't seem to cause any additional issues.

**Comment by jackmoore** [comment]
There should be scrollbars when overflowY is set to visible, however the plugin shouldn't be setting the overflow to visible unless it determines the height being set exceeds the max-height.

So for whatever reason, the plugin seems to be calculating the wrong max-height for your site.  I'm not sure I'll be able to fix it, since I can't reproduce the problem with IE10 and I don't see an obvious problem with the code.  However, I do believe your report about the issue as I'm not surprised this might happen in IE.

**Comment by JoeMoon5** [comment]
Here's the source of my text-area, which is a .Net server-side control. Maybe it will help with testing:

    <textarea name="ctl00$ph_Column$txtMyTitle" class="textbox resizable" id="txtEDATitle" style="width: 95%; height: 32px; -ms-overflow-y: hidden;" rows="2" cols="20" data-autosize-on="true">Testing</textarea>

Several of these things are auto-generated, like Height and the data-autosize-on. I notice the script exits out if that data attribute exists. Could that be the source of the problem?

**Comment by adam-lynch** [comment]
+1. Found in IE11.
