### ISSUE TITLE
Autosize textareas in Bootstrap modals

### ISSUE THREAD

**Issue by patrickbrouwers** [jackmoore/autosize#231]
When using autosize (3.0.6) on a textarea inside a modal, there's some unexpected behaviour:

- I bind the autosize to the textarea when the modal is opened (it's a modal loaded through ajax)
-  `overflow: hidden;word-wrap: break-word; resize: none;` are set on the element, but the height is not set
- Only when I enter inside the textarea the height is set.
- When I use the same thing outside the modal it works perfectly.

**Comment by jackmoore** [comment]
My guess would be that you are assigning autosize to the textarea at a point where it's height can not be determined: http://www.jacklmoore.com/autosize/#faq-hidden

**Comment by patrickbrouwers** [comment]
Thanks, was able to resolve it, using:

```
$modal.on('shown.bs.modal', function () {
    var textarea = document.querySelectorAll('textarea');
    autosize(textarea);
    autosize.update(textarea);
});
``

**Comment by chenweiyj** [comment]
@patrickbrouwers I use your last code and it works in the modal. However, the user will see the change when the height is changed. I think the user experience is not good. 

In this case, I have a table, which will pop out a modal after the click. The modal is shared with different data. So the textarea in the modal is shared as well. 

How to make the height change before the modal pops up in order to make the user not see the sudden change of the textarea height?

**Comment by coolboy4598** [comment]
@chenweiyj well, I have an answer for you....is very simple...try to do autoresize.update(ele) after assigning data to your table. and you are done...It worked for me.
(this will work because table will take height before showing on modal as it has content)
:)
