### ISSUE TITLE
Need support to let some space between screen bottom and cursor.

### ISSUE THREAD

**Issue by jayadeepk** [jackmoore/autosize#237]
The page scrolls down only when I press return and the cursor is at the bottom of the screen. This affects the design of my project as I need to let some whitespace between the text and the screen bottom while typing.

Can anyone suggest on how I can do this?
You can also make your suggestions for the same question in [stackoverflow](http://stackoverflow.com/questions/27988979/bottom-screen-margin-to-auto-expanding-textbox).

**Comment by Llaume** [comment]
This will be a great feature, I'm looking for this too. When you have footer fixed, the textarea is hidden by the footer when growing.

**Comment by jackmoore** [comment]
What's wrong with using bottom padding or margin on the textarea?  I feel like this is out of scope of what this script should be handling.

**Comment by Llaume** [comment]
I've created an example : https://jsfiddle.net/8Lw2Lryw/
Sadly padding-bottom didn't fixed this. The active typing line is at the end of the page and is hidden by the footer.

**Comment by jackmoore** [comment]
I see now, thanks for the demo.  I'm afraid I don't see any practical way to achieve what you are looking for.  Adding a buffer area to the bottom of autosize isn't going to help anything because it's the browser that determines how close the input caret can be to the bottom of the window.

The only thing I can think of as a work around would involve getting the caret position, but there's no api for that so it would be convoluted.  Then change the document/overflow parent scrollTop so that it scrolls the caret into a more desirable distance from the bottom of the document, based on the caret coordinates.

So it's probably technically possible, but it would be way more work than I would feel comfortable doing for a frequently fired event, and outside of the scope of what autosize should be responsible for.  If you were to write something like this, there is no reason it would have to be incorporated into Autosize's itself because it could probably be attached through the resized event (`autosize:resized`).  My guess is that such a script wouldn't involve Autosize at all because it's all based on caret position, which Autosize has no need to track.
