### ISSUE TITLE
Jumpy behavior on Nokia Lumia - Win 8.1 - IE Mobile

### ISSUE THREAD

**Issue by joaocunha** [jackmoore/autosize#239]
When one finishes typing the first line and it wraps, the screen starts jumping/bouncing at each keypress.

A small video to show it: http://recordit.co/fRtfisND75

**Comment by joaocunha** [comment]
@jackmoore well, it still jumps horizontally (wth?!) if the page has no viewport meta tag.

http://recordit.co/ECkyBetIRL

I temporarily sniffed the UA over here, but why exactly did you add the scroll check in the first place? Which browsers required that fix? Maybe we can improve the approach.

**Comment by jackmoore** [comment]
In order to use a single textarea element (vs. creating a cloned textarea element and taking measurements from that), the script changes the textarea height to 'auto', enables scrolling, and calculates a new height based on the height plus scrollHeight.  But this can change the height of the page, and cause jumpy scrollbar positioning.  So I save the original scroll height before changing the textarea height to auto, and after setting the new height, I restore the scroll position.

**Comment by jackmoore** [comment]
Having a cloned element avoids any sort of scroll-position issues, but it creates a lot of hard problems with getting the size exactly right.

**Comment by joaocunha** [comment]
Yes, this definitely something that needs to be improved. The `window.addEventListener('resize', update);` bit prevents page scrolling on Android Browser (Samsung Galaxy II) - it keeps pushing it to the top.
