### ISSUE TITLE
Set height in em rather then px

### ISSUE THREAD

**Issue by nazar-pc** [jackmoore/autosize#251]
Sometimes font size might be used to change size of elements, would be nice to set height in `em` units based on current font size, so that if font size will change it will not cause disaster.
Listening to font-size changes is an overkill, updating autosize on font size change manually is not convenient as well.

**Comment by jackmoore** [comment]
JavaScript doesn't know what unit of measure you used, because getComputedStyle returns the pixel equivalent values.

**Comment by nazar-pc** [comment]
Yes, but you can take value in pixels and divide by font size in pixels, getting `em`s

**Comment by jackmoore** [comment]
Oh, sorry, I see what you are asking now.  It's is an interesting suggestion, but I don't know if it is something I'll pursue.  Just because the font-size of the textarea parent element changed, doesn't necessarily mean that the font-size of the textarea also changed.  And even if the textarea font-size was em-based, it doesn't mean that the height would scale correctly because the width might not change (was fixed, percent based, or already at it's maximum size).

**Comment by nazar-pc** [comment]
This will give font size of textarea, other font sizes of other elements are not interesting here:
```javascript
parseInt(getComputedStyle(textarea).fontSize)
```

Yes, it doesn't mean that height would scale correctly, but there are two options here.

If it works as now, then font-size change will 100% cause issues.

But if change height to be `em`-based, then while font-size is constant, nothing really changes comparing to what we have now, and if for some reason font-size changes, there is non-zero probability to do the right thing here) At least we can't do worse)

Also developer who making changes to font-size in runtime should be aware about widths as well, but we can't really do anything better here.
