### ISSUE TITLE
$('textarea').autosize() is working only clicking on debug in browser

### ISSUE THREAD

**Issue by ruchidalal** [jackmoore/autosize#258]
HI,

I have jsp page with textareas. I am using version 1.18.15 of the autosize plugin.
The textareas are 4 to 5 times bigger than the content. However, on click of debug in browser the textarea size is autocorrected.
If I work  with the earlier versions(1.16.20) of the plugin, the content is cut for larger textareas.
Also, my textarea in inside an accordion view
Css properties set: 
textarea {
		border:2px solid #ccc;
		resize: none;
	}

	.autosize {
		vertical-align: top;
		-webkit-transition: height 0.2s;
		-moz-transition: height 0.2s;
		transition: height 0.2s;
		background-color: #f3f3f3;
}

I am not sure what am I missing in what appears to be a simple requirement.

**Comment by jackmoore** [comment]
If it's bigger than it should be, then that probably means that it calculated the width of the textarea at the time autosize was applied is smaller than when the textarea is visible.  This was probably because the textarea was not part of the document flow at the time autosize was applied (maybe because the accordion was collapsed?)

Does the textarea work as expected when it's not in the accordion?

**Comment by ruchidalal** [comment]
Yes, it worked when not in  accordion. By default the panels are collapsed. But I have applied the autosize on textareas before the accordion view. Do I need to  apply it every time on click of accordion ? Or is there a different way to achieve autosize textareas in accordion ?
