### ISSUE TITLE
Won't resize after append.

### ISSUE THREAD

**Issue by virik** [jackmoore/autosize#264]
Hi, I love your little plugin.

I'm having some problems with resizing a bunch of textareas after adding them with jQuery .append. After all the elements have been appended, I run the code below:

var textarea = $('#project-tasks').find('textarea');
autosize(textarea);

The textareas keep their 1-row height, until I type something in them, or resize my window.

How can I make them resize automatically after append?

Br,
Virik

**Comment by jackmoore** [comment]
That sounds like it should work, so I suspect you are leaving out critical information.  Are you sure the textarea elements are part of the document flow before you call autosize?  If you make a small demo in something like JS fiddle that reproduces issue, I'd be happy to have a look at it.

**Comment by virik** [comment]
I haven't used JS fiddle before, but it's something like this - https://jsfiddle.net/3s2m5raa/
There is an error in the code tho. Autosize not defined.

**Comment by jackmoore** [comment]
Updated it so that autosize is present, worked fine:
https://jsfiddle.net/3s2m5raa/1/

**Comment by virik** [comment]
In my code, it seems that autosize is fired before the append function is completed. I need to add some sort of callback.

Thank you for guiding me in the right direction.

**Comment by virik** [comment]
Hi Jack.

It seems that it's bootstrap tabs that cause the problem. Click on messages in this fiddle. The textarea expands when typing in it, but not before.

https://jsfiddle.net/DTcHh/12701/

**Comment by jackmoore** [comment]
It's because the textarea isn't in the document flow because the accordion panel has a display of none when autosize is assigned:
http://www.jacklmoore.com/autosize/#faq-hidden

Autosize can't take the width and height of the textarea element if it, or an ancestor element has display: none, or has been detached from the DOM.

I updated the example CSS to hide the accordion panel using a height of 0, rather than display: none.

https://jsfiddle.net/DTcHh/12702/

Also you could attach an onclick handler to the tabs that re-called autosize when clicked.

**Comment by virik** [comment]
Thank you very much :)
