### ISSUE TITLE
Initial height is two lines long

### ISSUE THREAD

**Issue by gschindler** [jackmoore/autosize#273]
Without any data inputted, textareas are initializing as if there are two lines of text. 

For example, one line of text equates 33px, but the textareas are dynamically set to 66px. Tried using min-height to accomplish this, and hacked around, but can't seem to figure out how to remove the secondary line. Any suggestions?

**Comment by jackmoore** [comment]
Sorry, I need to document this better.  You are probably seeing the textarea at the same height it would be if autosize was not being used.  Textarea elements have a rows attribute (default value is 2) that is used to determine the textarea height, in the absence of height set through CSS, or if a min-height set through CSS exceeds that effective height.  Autosize doesn't change the rows attribute value, leaving it open to use for setting the default height.

For example:

```
<textarea>Two rows</textarea>
<textarea rows='1'>One row</textarea>
```

The gist of what autosize is doing is asking the browser for the height the textarea would normally have, and adding to it however much overflow there would be.  To me this seems preferable to starting from zero, so that the autosized minimum height matches whatever the developer set their default textarea height to be.

**Comment by gschindler** [comment]
Thanks for the quick response. I was unaware of that attribute--worked great. Thanks again.
