### ISSUE TITLE
Textarea padding is not taken into account for multiline placeholders

### ISSUE THREAD

**Issue by danny-wu** [jackmoore/autosize#283]
jsfiddle: https://jsfiddle.net/c58xLc57/9/

The height set for the textarea is exclusive of the `padding` when the placeholder is multiline. Unfortunately setting a `min-height` isn't an attractive option as the length of the placeholder is variable.

v1 properly takes into account padding in this case: https://jsfiddle.net/c58xLc57/10/

**Comment by jackmoore** [comment]
Whoa, thats interesting (and browser dependent)!  I assume you are using a blink or webkit browser.  Firefox crops off any overflowing placeholder text, which is what I expected to see.  I believe all browsers used to crop the placeholder text, rather than allowing it to be scrollable, but I may be wrong about that.

Autosize v1 was able to account for placeholder size because it used placeholder text as actual text in the mirrored textarea element for making measurements.  Autosize v2 and up have not used a mirrored element for various reasons, and instead have a simpler mechanism for determining what the height should be.  This is mainly just taking the default height and adding the scroll height, plus a little offset stuff depending on box-sizing.

The discrepancy in this case comes down to the webkit/blink giving slightly different numbers depending if it's normal text vs placeholder text.  For example, try scrolling these two textareas:

https://jsfiddle.net/5e9sL8ng/

Autosize is not used at all in this fiddle, but you'll see the same situation where the padding is not respected for the placeholder text.  This is just a quirk (I feel like it's a bug) of the rendering engine.  

It would be nice if Autosize smoothed out these inconsistencies, but that is out of scope for what I want Autosize to be.  I aim to have Autosize be small, simple, with a singular goal to expand the textarea element just as the browser would if textarea elements could have an automatic height.  In this situation, it seems to be doing just that.

That being said, feel free to continue using v1.  The vast majority of sites never seem to run into any issue with it, but I didn't feel comfortable continuing down that path because it is impossible to do exact mirroring depending on the CSS involved.  The only way to copy the styles of the visible textarea element is to use getComputedStyle, which is aptly named.  Depending on the setup, the actual style could change after the computed style was taken, and I had no efficient way monitoring for those changes in JavaScript.

**Comment by danny-wu** [comment]
Aha, thank you for the explanation! :smile: Now I understand how v1 was able to account for the placeholder text.

My issue actually isn't clipping (but that is very interesting!). Rather, I want the textarea to expand to fully show the placeholder, so I'll continue to use v1 :)
