### ISSUE TITLE
Disabled textareas don't get resized (FF + IE)

### ISSUE THREAD

**Issue by dshorowitz** [jackmoore/autosize#301]
If you disable your textarea, but it still receives new props (through a function call, for example), on Firefox and IE it won't get autoresized. Seems to be related to a known bug in FF: https://bugzilla.mozilla.org/show_bug.cgi?id=867418 in which dispatchEvent doesn't dispatch events on disabled form controls.

Any workaround?

**Comment by bohnetn** [comment]
I am having same issue in IE with disabled textareas originally hidden in the DOM.  When textareas become visible the workaround (for the users) is to minimize IE and then maximize IE window.  This seems to then autoresize the textareas that are disabled and previously hidden - interesting, but don't know why??    I tried doing window.resizeTo() or window.resizeBy() in js but other than a very annoying flash on the screen, it did not change the autoresize behaviour.

Also would appreciate other's insights, solutions.
Otherwise, it works great!!

Many Thanks!

**Comment by jackmoore** [comment]
@dshorowitz Hi, sorry for the late response.  The most recent release should resolve this issue.  If you change a disabled textarea element's value using JavaScript, use autosize.update(textareaElement) to trigger the resize, rather than dispatching the custom event (autosize:update).  Autosize was updated not to use dispatchEvent when calling it's methods methods (autosize.update & autosize.destroy) to work-around Firefox dispatchEvent bugs.

**Comment by bohnetn** [comment]
Yes, great!
That did indeed fix it.

Many thanks.
