### ISSUE TITLE
Printing adds scroll bar and not all lines are visible

### ISSUE THREAD

**Issue by nickwuk** [jackmoore/autosize#303]
When printing not all content lines are visible, and a vertical scroll bar is added in IE11.

**Comment by jackmoore** [comment]
If the content isn't visible, it's probably due to the CSS print typographic styles being different than screen styles.  There isn't much autosize can do about that, as there isn't an event broadcast when style changes.

If I was trying to print a textarea element, I would probably hide that textarea element for print media and instead mirror that text into a print-visible/screen-hidden div using the onInput event handler on the textarea element.
