### ISSUE TITLE
Initial height is still wrong

### ISSUE THREAD

**Issue by temirfe** [jackmoore/autosize#304]
my textarea height is 25px (given by css), but when autosize is fired the height becomes 121px. Have tried all three ways described on official site, but with no luck.

**Comment by johnnydoe82** [comment]
Same here!

**Comment by jackmoore** [comment]
Come on guys, you know you have to provide more information than this.

**Comment by jackmoore** [comment]
Create a demo with the minimum needed to reproduce the issue and I'll promise to look into it.  I assume the issue is cross-browser, but if not leave me your browser&version info too.

**Comment by johnnydoe82** [comment]
Sorry for not providing more information in the first place :/

This issue seems to happen on your very own demo of autosize: http://www.jacklmoore.com/autosize/ The textarea is always two lines high, even when it's completely empty. 
I think too, that this is a cross-browser issue. This happens for me on Chrome 51/Windows 10, as well as on Firefox 47/Windows 10. In Linux for current versions of Chromium and Firefox it's the same.

If you need a demo with the minimum needed to reproduce the issue, I can try to set this up the next days.

**Comment by jackmoore** [comment]
The 2-line-height is based on the textarea's innate rows attribute value, this is covered in the documentation:

{quote}
The rows attribute can also be used to specify a minimum height. The rows attribute has a default value of 2, so to make the textarea smaller than that you'll need to set the value to 1. Example: `<textarea rows='1'></textarea>`
{quote}

I try not to emphasis rows too much because it's not something that Autosize cares about directly (Autosize never accesses the rows value).  To determine what the height of the textarea should be, Autosize sets the textarea height style to 'auto' and then takes the scrollHeight.  The scrollHeight is going to have a minimum height of the CSS min-height style or rows times line-height, whichever is greater (plus padding, which Autosize will account for).  This is just how the property value is calculated by the DOM.

Setting a CSS style for height isn't going to impact Autosize's measurement because it sets the height style to 'auto' to make sure that the value for scrollHeight isn't larger than it needs to be for the content.

**Comment by jackmoore** [comment]
You can lower the default rows value from 2 to 1, but anything lower than that is treated like an invalid value and it will default back to 2.  This makes sense to me because you want at least one line for the cursor to occupy.

**Comment by temirfe** [comment]
thanks @jackmoore rows attribute was the case

**Comment by johnnydoe82** [comment]
Yes thanks @jackmoore ... overseen this in the docs :/

**Comment by jackmoore** [comment]
👍

**Comment by zcoding** [comment]
thks
