### ISSUE TITLE
Provide option to resize hidden textareas, too

### ISSUE THREAD

**Issue by doits** [jackmoore/autosize#312]
I've a textarea that is hidden. This is not resized by default since version 3.0.3 afaik.

It might happen I show this textarea to an user. Of course then I want it to be resized. Edit: I can manually use `autosize.update` for that at least - it works that way.

An option to still resize it if hidden would work for me, something like:

    autosize($('textarea'), { resize_hidden: true })

Btw: I'm not sure why hidden elements are prevented to be resized. When I call `autosize()` on an element I want it to be resized. If I do not want hidden elements to be resized I don't pass them to `autosize`, eg `autosize($('textarea:visible'))`.

One could argue there should be a way to stop and start autosize on an element to give some more control for dynamic elements, like

    $('textarea').trigger('autosize:pause') // stop resizing
    $('textarea').trigger('autosize:resume') // resume resizing and resize it once
                                             // (because content might have changed on pause)

... but I think by default it should resize everything I pass to it.

So all in all I think hidden elements should be resized by default and a pause/resume mechanism should be implemented, so the OP of #155 can disable resizing dynamically (or maybe even simply by not passing invisible elements to `autosize` if the visibility is not dynamic).

**Comment by jackmoore** [comment]
Autosize can not measure what the size is supposed to be for an element that is not in the document flow (because it has been hidden or detached), because it depends on DOM methods to return computed sizes that are based on the layout.  Believe me, I would not have the hidden/detached stipulation if I could prevent it.

Autosize has no way of knowing when the element is back in the document flow, there is no event listener for that situation (the only way for me to observe that change would be to inefficient poll for it).  Because of this, when you add the element back to the document flow you'll need to tell autosize to recalculate the size.  For example:

```
var $ta = $('textarea#ex');
$ta.show();
autosize.update($ta);
```

I doubt I'll be adding pause and resume events, I don't see a strong use case for them.  Autosize is effectively paused when the textarea is not receiving input, and there is a destroy method to remove autosize entirely from an element.
