### ISSUE TITLE
error and warning after "gulp --production"

### ISSUE THREAD

**Issue by haheute** [jackmoore/autosize#322]
I use laravel elixir / gulp@3.9.1 to minify css and js. 
When using `gulp --production` I see this error in chromium's console:

`all-7ef57c0cf5.js:5 Uncaught TypeError: Cannot read property 'height' of undefined`

Without `--production` the error does not appear. I don't know what could cause this...
The function itself is called inside a 'document ready':

    $(document).ready(function(){
        autosize($('textarea'));
    });

The textarea looks so:

    <textarea name="comment" class="fw" rows="5" required="required">{{ old('comment') }}</textarea>

The autosizing seems to work, but I would like to fix this error message.

**Comment by jackmoore** [comment]
It sounds like there is a problem with the minification process (assuming it's coming from autosize's code).  It seems unlikely I rarely run into bug introduced in build-steps, but I would check to make sure you are using the latest versions of your toolchain in case there was a bug with the minifier.

If that doesn't resolve the issue I'll need a reproducible demo to debug further, because I probably am not going to try to reproduce this myself since it could be time consuming for something that could end up being a toolchain problem instead of a bug with autosize.

**Comment by haheute** [comment]
I tried again with `autosize.js` instead of `autosize.min.js`. 
Now it looks good, no error messages.
