### ISSUE TITLE
Method update not working at first init

### ISSUE THREAD

**Issue by rorc** [jackmoore/autosize#324]
Trying to update textarea for full height, but have nothing: `autosize.update(autosize($('textarea')));`
Textarea getting full height only after start typing...

**Comment by jackmoore** [comment]
Sorry, this isn't enough information to diagnose your problem, a demonstration would be required.

My guess is that your textarea is hidden or disabled at the time you assign autosize.  If that's the case, you can read more about that here: http://www.jacklmoore.com/autosize/#faq-hidden

It's also possible that you changed the value of the textarea after using JavaScript or styles/layout involving the textarea element, neither of which trigger events that autosize is able to listen for in order to update the textarea size.

Also, it should never be necessary to call update after immediately assigning, so I would reduce your code to this: `autosize($('textarea'));`

**Comment by rorc** [comment]
Yea, sorry, its my inattention.
I use autosize with Vuejs, and called autosize immediately before dom update after textarea shows.
