### ISSUE TITLE
Great plugin how do i implement with ctrl + enter, rather then enter?

### ISSUE THREAD

**Issue by kgrosvenor** [jackmoore/autosize#325]

**Comment by jackmoore** [comment]
Sorry, autosize isn't doing anything that specific.  It listens to the input event instead of specific key combinations.  When input fires, it removes the inline height style from the textarea element and takes the scrollHeight.  That scrollHeight is used as a basis for setting a new height style.  I don't think there is an easy way of getting what you are looking for out of Autosize.

**Comment by cyberzilla** [comment]
maybe u can use simple trick
```

ctrl + enter = fire autosize 
(shift + enter) just change e.shiftKey

$(function(){
autosize($('textarea'));
$("textarea").on("keydown",function(e){
    if(!e.ctrlKey && e.keyCode===13){
	e.preventDefault();
	console.log("only enter");
     }
});
});
```

Hope This Help your problem :)

**Comment by kgrosvenor** [comment]
@cyberzilla Thanks for this mate, i did manage to use autosize and add ctrl + enter key in the end using Vue.js and a little jQuery :)

Thank you for your recommendation its pretty much exactly what i went for!
