### ISSUE TITLE
Autosize not working with webpack in Laravel

### ISSUE THREAD

**Issue by udanpe** [jackmoore/autosize#350]
resources/assets/js/app.js
require('autosize/dist/autosize');
autosize($('.textarea-auto-height'));
npm run dev
Uncaught ReferenceError: autosize is not defined
    at Object.<anonymous> (app.js:11026)
    at __webpack_require__ (app.js:20)
    at Object.<anonymous> (app.js:11008)
    at __webpack_require__ (app.js:20)
    at app.js:63
    at app.js:66

if change autosize.js all working
autosize($('.textarea-auto-height'));
// module.exports = autosize;

**Comment by jackmoore** [comment]
It's in UMD module format, so you'll want to assign your require to a variable.  Some something like `const autosize = require('autosize/dist/autosize')`.  You should also be able shorten that to `const autosize = require('autosize')` because the package.json lists /dist/autosize.js as the entry/main file.

**Comment by udanpe** [comment]
jackmoore, Thanks!

**Comment by gatesplan** [comment]
Looks like same issue happens to me, but not working with `const autosize = require('..');`

in `resources/js/app.js` file, I wrote
`const autosize = require('autosize/dist/autosize');`

and repacking.. 

in html page,
`autosize(document.getElementById('ta')` makes an error Uncaught ReferenceError

**Comment by jackmoore** [comment]
@gatesplan I think the problem is that when you import autosize as a module it is no longer provided as a global (this is just how the UMD modules work, see the conditional logic for that at top of the dist/autosize file). You should make that global yourself if you want to use autosize outside of the scope in which it was imported.

**Comment by nemchik** [comment]
If anyone else comes looking for another way to do this:

```javascript
import autosize from "autosize";
global.autosize = autosize;
```

**Comment by RahulKmOfficial** [comment]
here a simple solution
in your `resources/js/app.js`
add this code 
`autosize = require('autosize');

![Screenshot 2020-04-12 04:10:36](https://user-images.githubusercontent.com/22678382/79056526-12ffe700-7c75-11ea-818f-43806c663ae3.png)
`
