### ISSUE TITLE
fastdom implementation

### ISSUE THREAD

**Issue by fernandodelgadomtech** [jackmoore/autosize#378]
Hello,

I was looking at my application's performance and I noticed autosize is called quite a few times during the rendering process and I was wondering if the library could benefit from using [fastdom](https://github.com/wilsonpage/fastdom) to reduce the number of reflows on the DOM?

**Comment by jackmoore** [comment]
Hi Fernando, thanks for the suggestion.

I agree that autosize causes a lot of activity, it's unfortunate and I would love to find a more efficient way of handling it. However, I don't think fastdom will be able to offer much assistance except for a narrow case of having autosize on many elements while resizing the width of the page. In that use case you could probably find regain some performance by batching. For normal use (typing in an autosize element), I don't think there is much that can be batched. Autosize is only working on that one element, and it's operations (measure, mutate, measure, mutate...) have to happen in sequence. 

The browser will already batch various style changes together if they happen in quick succession without measuring. I actually have to work around that optimization in the `changeOverflow` function (see the source for notes about it), where in order to get an accurate measurement after style change, I'm forced to hard-trigger a reflow because the browser will not have flushed those style changes fast enough.

**Comment by fernandodelgadomtech** [comment]
Makes perfect sense, thanks for taking the time to an
