### ISSUE TITLE
The account name input field collapses when trying to insert prohibited characters

### ISSUE THREAD

**Issue by sergeivaskin1991** [jackmoore/autosize#400]
there is a regex validation that does not allow certain characters to be entered. if you select all the text and try to insert a character that does not go into the regex, then the input collapses #

https://user-images.githubusercontent.com/60850945/197768893-5aced3a2-ed0c-4afb-8b7c-dd3f09337c9b.mov

**Comment by jackmoore** [comment]
There is no regex is autosize. I think you either have the wrong project, or are using something built on top autosize.

**Comment by sergeivaskin1991** [comment]
https://codesandbox.io/s/flamboyant-wood-krnk7u?file=/src/component.tsx

Here is a link to a demo. here it just shows how the auto-sized textbox collapses when used with a regex. we ourselves use the regular expression along with the autosize library. we don't want this behavior. it is necessary that if a character is entered that is not in the regex, the autosize behavior does not change, but does not collapse

**Comment by jackmoore** [comment]
Ah, I think I understand now. This is outside the scope of autosize. I spent too long trying to get this to work from the outside but I felt like it was possible and wanted to see it through. See the updated sandbox: https://codesandbox.io/s/white-dawn-czyc7x

The main points are that the `oninput` event cannot be cancelled, so whatever the user types (or pastes) will become the value of the element. The best you can do is quickly strip the invalid text out after the input event has fired. However, Autosize is also listening to the input event to do its work.

I worked around that by setting up an input event handler before autosize that calls `stopImmediatePropagation` on the event if the input text does not pass validation. This prevents autosize from receiving the event, but it does not stop the invalid text from becoming the value of the textarea. React needs to rerender the component to sync what is shown on screen with the value it has in local state. However, passing the current local state for value to setValue isn't going to trigger a rerender because it's the same value. React sees this as an unnecessary rerender and discards it, not knowing that the value on the screen no longer matches local state. This is what I added a method to force a rerender when validation fails.

Sorry, I know all that is complicated. I hope that will all make sense once you review the code and test it in the sandbox.

**Comment by jackmoore** [comment]
You could modify the autosize script to take in a validation function in order bypass needing to call stopImmediatePropagation, but that's too niche of a use case for me to make it part of the official release.

**Comment by jackmoore** [comment]
It dawned on me that I didn't need to trigger a rerender since React already has the desired local state for value, we only need to get the onscreen value to reflect the value React already has as local state. I replaced the forced rerender with directly assigning the local state value to the value of the textarea element: https://codesandbox.io/s/prod-cookies-ebwusm?file=/src/App.tsx

**Comment by sergeivaskin1991** [comment]
It is fantastic!! Thanks a lot!!!! You helped a lot. Great respect, low bow and respect! 💪🏻 👍🏻
